"""changesmth

Revision ID: 2efae9b29b56
Revises: 934f48b2b0ff
Create Date: 2023-09-08 00:39:05.231224

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2efae9b29b56'
down_revision: Union[str, None] = '934f48b2b0ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bookings_id', table_name='bookings')
    op.alter_column('hotels', 'services',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('hotels', 'image_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_hotels_id', table_name='hotels')
    op.drop_index('ix_rooms_id', table_name='rooms')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_rooms_id', 'rooms', ['id'], unique=False)
    op.create_index('ix_hotels_id', 'hotels', ['id'], unique=False)
    op.alter_column('hotels', 'image_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hotels', 'services',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.create_index('ix_bookings_id', 'bookings', ['id'], unique=False)
    # ### end Alembic commands ###
