version: '3.8'

name: booking

services:

  database:
    container_name: database
    image: postgres:14.2-alpine
    env_file:
      - .docker.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    expose:
      - ${DB_PORT}
    volumes:
      - booking_data:/var/lib/postgresql/data

  server:
    image: booking-image
    build:
        context: .
        dockerfile: Dockerfile
    env_file:
      - .docker.env
    command: make migrate upserver
    expose:
      - 8000
    depends_on:
      - redis
      - database
    deploy:
      replicas: 2

  nginx:
    container_name: nginx
    image: nginx-image
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./app/static:/usr/src/app/static
    depends_on:
      - server

  redis:
    container_name: redis
    image: redis-image
    build: ./redis
    expose:
      - 6379

  celery:
    container_name: celery
    image: booking-image
    env_file:
      - .docker.env
    command: make upcelery
    volumes:
      - ./app/static:/usr/src/app/static
    depends_on:
      - redis

volumes:
  booking_data:
    external: true

